# Ia que fez a maior parte, o resto peguei das outras atividades, não sei mexer com docker

# Use an official Haskell image as a base image
FROM haskell:latest

# Set up the working directory
WORKDIR /workspace

# Install sqlite3
run apt-get update && apt-get install -y sqlite3